# Generated by Django 6.0.1 on 2026-01-09 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('generator', models.CharField(blank=True, max_length=100, null=True, verbose_name='제너레이터')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='제목')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='링크')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='언어')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='발행자')),
            ],
            options={
                'verbose_name': '뉴스 채널',
                'verbose_name_plural': '뉴스 채널',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='제목')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='링크')),
                ('guid', models.CharField(blank=True, max_length=5000, null=True, verbose_name='GUID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('source_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='신문사 이름')),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='신문사 URL')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newschannel', verbose_name='뉴스 채널')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
